#' Turn a tall data frame from makeTallDataFrame into a wide data frame
#'
#' This function creates a \code{data.frame} containing data for different data types in a form suitable for further statistical modelling in R.
#'
#' @param df A \code{data.frame} in tall format generated by \code{makeTallDataFrame}
#' @return A \code{data.frame} in wide format
#' @export
makeWideFromTallDataFrame <- function(df) {

  #create matrix
  output.df <- df %>% transmute(CCLE_name, fn=paste(ID,Type,sep='_'), value) %>% spread(fn, value)

  #reorder columns
  output.df <- output.df %>% dplyr::select(CCLE_name, ends_with('_resp'), everything())

  #make mutation fields into factors
  output.df <- output.df %>% mutate_each(funs(as.factor), ends_with('_hybcap|_cosmicclp'))

  return(output.df)

}
