#' Make a RespVsResp wide data frame
#'
#' This function creates a pivotted \code{data.frame} with the output of the makeRespVsRespDataFrame function
#'
#' @param df A \code{data.frame} object generated by the makeRespVsRespDataFrame function
#' @return A pivotted \code{data.frame} with one response variable per column
#' @export
makeWideFromRespVsRespDataFrame <- function(df) {

  df %>% dplyr::select(-Type, -original) %>% spread(ID, value)

}
